/**
* Bamba API
* SDK for Bamba API
*
* The version of the OpenAPI document: 1.3.2
* Contact: desarrollo@vivebamba.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.vivebamba.client.models


import com.squareup.moshi.Json

/**
 * 
 * @param id 
 * @param name Benefit
 * @param brief Plan benefit summary
 * @param state Cancellation status
 * @param canceledAt The date and time (ISO 8601 format) of cancellation
 */

data class CancellationResponse (
    @Json(name = "id")
    val id: java.util.UUID? = null,
    /* Benefit */
    @Json(name = "name")
    val name: kotlin.String? = null,
    /* Plan benefit summary */
    @Json(name = "brief")
    val brief: kotlin.String? = null,
    /* Cancellation status */
    @Json(name = "state")
    val state: kotlin.String? = null,
    /* The date and time (ISO 8601 format) of cancellation */
    @Json(name = "canceledAt")
    val canceledAt: java.time.OffsetDateTime? = null
)

