/**
 * Bamba API
 *
 * SDK for Bamba API
 *
 * The version of the OpenAPI document: 1.3.5
 * Contact: desarrollo@vivebamba.com
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.vivebamba.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param id UUID for the service
 * @param name Benefit
 * @param sku 
 * @param brief Plan benefit summary
 * @param state Status
 * @param validFrom The date and time (ISO 8601 format) of start of validity of the subscription
 * @param validTo The date and time (ISO 8601 format) of end of validity of the subscription
 * @param certificateLink Temporary url to download the certificate of benefits in pdf format
 */

data class CustomerServices (

    /* UUID for the service */
    @Json(name = "id")
    val id: kotlin.String? = null,

    /* Benefit */
    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "sku")
    val sku: kotlin.String? = null,

    /* Plan benefit summary */
    @Json(name = "brief")
    val brief: kotlin.String? = null,

    /* Status */
    @Json(name = "state")
    val state: kotlin.String? = null,

    /* The date and time (ISO 8601 format) of start of validity of the subscription */
    @Json(name = "validFrom")
    val validFrom: java.time.OffsetDateTime? = null,

    /* The date and time (ISO 8601 format) of end of validity of the subscription */
    @Json(name = "validTo")
    val validTo: java.time.OffsetDateTime? = null,

    /* Temporary url to download the certificate of benefits in pdf format */
    @Json(name = "certificate_link")
    val certificateLink: kotlin.String? = null

)

