/**
* Bamba API
* SDK for Bamba API
*
* The version of the OpenAPI document: 1.2.6
* Contact: desarrollo@vivebamba.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.vivebamba.client.models


import com.squareup.moshi.Json

/**
 * 
 * @param name The customer's name
 * @param lastName The customer's last name
 * @param secondLastName The customer's second last name
 * @param cellphone The customer's cellphone number
 * @param email The customer's email
 * @param birthdate The customer's birthdate on yyyy-mm-dd format
 * @param gender The customer's gender, M for Male and F for Female
 */

data class Customer (
    /* The customer's name */
    @Json(name = "name")
    val name: kotlin.String,
    /* The customer's last name */
    @Json(name = "lastName")
    val lastName: kotlin.String,
    /* The customer's second last name */
    @Json(name = "secondLastName")
    val secondLastName: kotlin.String,
    /* The customer's cellphone number */
    @Json(name = "cellphone")
    val cellphone: kotlin.String,
    /* The customer's email */
    @Json(name = "email")
    val email: kotlin.String,
    /* The customer's birthdate on yyyy-mm-dd format */
    @Json(name = "birthdate")
    val birthdate: java.time.LocalDate,
    /* The customer's gender, M for Male and F for Female */
    @Json(name = "gender")
    val gender: kotlin.String
)

