/**
* Bamba API
* SDK for Bamba API
*
* The version of the OpenAPI document: 1.3.0
* Contact: desarrollo@vivebamba.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.vivebamba.client.models

import com.vivebamba.client.models.InlineResponse422Errors

import com.squareup.moshi.Json

/**
 * 
 * @param errors 
 */

data class InlineResponse422 (
    @Json(name = "errors")
    val errors: kotlin.collections.List<InlineResponse422Errors>? = null
)

