/**
* Bamba API
* SDK for Bamba API
*
* The version of the OpenAPI document: 1.0.0
* Contact: desarrollo@vivebamba.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.vivebamba.client.models


import com.squareup.moshi.Json

/**
 * 
 * @param from The customer cellphone
 * @param text The text of the message
 * @param sentAt The date and time (ISO 8601 format) when the message was sent
 */

data class Message (
    /* The customer cellphone */
    @Json(name = "from")
    val from: kotlin.String? = null,
    /* The text of the message */
    @Json(name = "text")
    val text: kotlin.String? = null,
    /* The date and time (ISO 8601 format) when the message was sent */
    @Json(name = "sentAt")
    val sentAt: java.time.OffsetDateTime? = null
)

