/**
* Bamba API
* SDK for Bamba API
*
* The version of the OpenAPI document: 1.2.1
* Contact: desarrollo@vivebamba.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.vivebamba.client.models

import com.vivebamba.client.models.Customer
import com.vivebamba.client.models.OrderProducts

import com.squareup.moshi.Json

/**
 * 
 * @param customer 
 * @param products The collection of SKU from the products selected by the customer
 */

data class Order (
    @Json(name = "customer")
    val customer: Customer,
    /* The collection of SKU from the products selected by the customer */
    @Json(name = "products")
    val products: kotlin.collections.List<OrderProducts>? = null
)

