/**
* Bamba API
* SDK for Bamba API
*
* The version of the OpenAPI document: 1.2.4
* Contact: desarrollo@vivebamba.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.vivebamba.client.models


import com.squareup.moshi.Json

/**
 * 
 * @param sku 
 */

data class OrderProducts (
    @Json(name = "sku")
    val sku: kotlin.String? = null
)

