/**
 * Bamba API
 *
 * SDK for Bamba API
 *
 * The version of the OpenAPI document: 1.3.4
 * Contact: desarrollo@vivebamba.com
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.vivebamba.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param mediaTypeKey Media type key to make the payment, available options CARD, TOKEN, PHONE_NUMBER, EMAIL, CLABE, CACAO, CUSTOMER_NUMBER, ACCOUNT_NUMBER
 * @param mediaTypeValue The value for the selected media type, example if mediaTypeKey is EMAIL here it goes customer@domain.com, also the tokenized card from payment gateways like OPENPAY
 * @param mediaDeviceId Needed for antifraud system, it is the device id from where the request is being sent
 * @param installments Intended for MSI (for is acronym in spanish) specification in the payment.
 */

data class PaymentParams (

    /* Media type key to make the payment, available options CARD, TOKEN, PHONE_NUMBER, EMAIL, CLABE, CACAO, CUSTOMER_NUMBER, ACCOUNT_NUMBER */
    @Json(name = "mediaTypeKey")
    val mediaTypeKey: kotlin.String,

    /* The value for the selected media type, example if mediaTypeKey is EMAIL here it goes customer@domain.com, also the tokenized card from payment gateways like OPENPAY */
    @Json(name = "mediaTypeValue")
    val mediaTypeValue: kotlin.String,

    /* Needed for antifraud system, it is the device id from where the request is being sent */
    @Json(name = "mediaDeviceId")
    val mediaDeviceId: kotlin.String? = null,

    /* Intended for MSI (for is acronym in spanish) specification in the payment. */
    @Json(name = "installments")
    val installments: kotlin.String? = null

)

