/**
* Bamba API
* SDK for Bamba API
*
* The version of the OpenAPI document: 1.3.2
* Contact: desarrollo@vivebamba.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.vivebamba.client.models


import com.squareup.moshi.Json

/**
 * 
 * @param mediaTypeKey Media type key to make the payment, available options CARD, PHONE_NUMBER, EMAIL, CLABE, CACAO, CUSTOMER_NUMBER, ACCOUNT_NUMBER
 * @param mediaTypeValue The value for the selected media type, example if mediaTypeKey is EMAIL here it goes customer@domain.com
 */

data class PaymentParams (
    /* Media type key to make the payment, available options CARD, PHONE_NUMBER, EMAIL, CLABE, CACAO, CUSTOMER_NUMBER, ACCOUNT_NUMBER */
    @Json(name = "mediaTypeKey")
    val mediaTypeKey: kotlin.String,
    /* The value for the selected media type, example if mediaTypeKey is EMAIL here it goes customer@domain.com */
    @Json(name = "mediaTypeValue")
    val mediaTypeValue: kotlin.String
)

