/**
* Bamba API
* SDK for Bamba API
*
* The version of the OpenAPI document: 1.1.0
* Contact: desarrollo@vivebamba.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.vivebamba.client.models


import com.squareup.moshi.Json

/**
 * 
 * @param description The description of the service
 * @param state The actual state of the service
 * @param validFrom The date and time (ISO 8601 format) of start of validity of the service
 * @param validTo The date and time (ISO 8601 format) of end of validity of the service
 * @param policyNumber The policy number of the customer service, some services does not have it
 */

data class Service (
    /* The description of the service */
    @Json(name = "description")
    val description: kotlin.String,
    /* The actual state of the service */
    @Json(name = "state")
    val state: kotlin.String,
    /* The date and time (ISO 8601 format) of start of validity of the service */
    @Json(name = "validFrom")
    val validFrom: java.time.OffsetDateTime,
    /* The date and time (ISO 8601 format) of end of validity of the service */
    @Json(name = "validTo")
    val validTo: java.time.OffsetDateTime,
    /* The policy number of the customer service, some services does not have it */
    @Json(name = "policyNumber")
    val policyNumber: kotlin.String? = null
)

