/**
* Bamba API
* SDK for Bamba API
*
* The version of the OpenAPI document: 1.2.2
* Contact: desarrollo@vivebamba.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.vivebamba.client.models

import com.vivebamba.client.models.Service

import com.squareup.moshi.Json

/**
 * 
 * @param sku The SKU from product related to the subscription
 * @param name The product name related to the subscription
 * @param state The state of the subscription
 * @param validFrom The date and time (ISO 8601 format) of start of validity of the subscription
 * @param validTo The date and time (ISO 8601 format) of end of validity of the subscription
 * @param relatedServices 
 */

data class Subscription (
    /* The SKU from product related to the subscription */
    @Json(name = "sku")
    val sku: kotlin.String,
    /* The product name related to the subscription */
    @Json(name = "name")
    val name: kotlin.String,
    /* The state of the subscription */
    @Json(name = "state")
    val state: kotlin.String,
    /* The date and time (ISO 8601 format) of start of validity of the subscription */
    @Json(name = "validFrom")
    val validFrom: java.time.OffsetDateTime,
    /* The date and time (ISO 8601 format) of end of validity of the subscription */
    @Json(name = "validTo")
    val validTo: java.time.OffsetDateTime,
    @Json(name = "relatedServices")
    val relatedServices: kotlin.collections.List<Service>
)

